version: 2.1

orbs:
  aws-cli: circleci/aws-cli@2.0
  aws-assume-role: airswap/assume-role@0.2.0

jobs:
  run_billing_tool:
    docker:
      - image: cimg/python:3.11.1
    parameters:
      slack_channel:
        type: string
        default: tech-devops-alerts-test
    steps:
      - checkout
      - aws-cli/setup
      - aws-assume-role/assume-role
      - run: python --version
      - run:
          name: Run AWS Billing
          command: |
            python -m pip install --upgrade pip
            pipenv install --system --deploy
            python ./handler.py
    environment:
      SLACK_CHANNEL: <<parameters.slack_channel>>

workflows:
  main-workflow:
    jobs:
      - run_billing_tool:
          context:
            - aws-org
            - slack
  weekly:
    triggers:
      - schedule: # Triggered workflow runs once a week
          cron: "0 10 * * 5"
          filters:
            branches:
              only:
                - master
    jobs:
      - run_billing_tool:
          slack_channel: alerts-bandstand-test
          context:
            - aws-org
            - slack
